stages:
 - dev
 - alpha
 - beta
 - live

job_for_dev:
  stage: dev
  script:
    - hostname
    - pwd
    - ls /var/www/clients/client3/web1/home/cleartech1/simple-deploy.sh
  only:
    - dev
  tags:
    - dev
  environment: dev

job_for_alpha:
  stage: alpha
  script:
    - hostname
    - pwd
  only:
    - alpha
  tags:
    - alpha
  environment: qa

job_for_beta:
  stage: beta
  script:
    - hostname
    - pwd
    - export PATH=/opt/remi/php56/root/bin/:$PATH && cd $HOME/web && git pull origin beta && php artisan migrate && php artisan asset:dist
  only:
    - beta
  tags:
    - beta
  environment: staging

job_for_live:
  stage: live
  script:
    - hostname
    - pwd
  only:
    - master
  tags:
    - live
  environment: production