stages:
 - dev
 - dev_node
 - alpha
 - alpha_node
 - beta
 - beta_node
 - live
 - live_node

job_for_dev:
  stage: dev
  script:
    - hostname
    - pwd
    - sh /var/www/clients/client3/web1/home/cleartech1/simple-deploy.sh
    - export PATH=/opt/remi/php70/root/bin/:$PATH && cd /var/www/clients/client3/web1/web && php artisan clear-compiled
    - export PATH=/opt/remi/php70/root/bin/:$PATH && cd /var/www/clients/client3/web1/web && php artisan optimize
  only:
    - dev
  tags:
    - dev
  environment: dev

node_job_for_dev:
  stage: dev_node
  script:
    - hostname
    - cd /var/www/clients/client3/web1/web
    - pwd
    - node --version
    - npm i
    - npm run build
    - find /var/www/clients/client3/web1/web/ -user root -exec chown 5004:5005 {} \;
  only:
    - dev
  tags:
    - sh1_clevercrew_docker
  image: node
  environment: dev

job_for_alpha:
  stage: alpha
  before_script:
    - php -v
    - export PATH=/opt/remi/php56/root/bin/:$PATH
  script:
    - hostname
    - pwd
    - php -v
    - cd $HOME/web && git pull origin alpha
    - cd $HOME/web && php artisan migrate --force --no-interaction
    - cd $HOME/web && php artisan asset:dist
    - cd $HOME/web && php artisan clear-compiled
    - cd $HOME/web && php artisan optimize
  only:
    - alpha
  tags:
    - alpha
  environment: qa

node_job_for_alpha:
  stage: alpha_node
  script:
    - export ALPHA_HOME=/home/bible_alpha
    - cd $ALPHA_HOME/web
    - npm install
    - npm run build
    - find $ALPHA_HOME/web -user root -exec chown 1002:1002 {} \;
  only:
    - alpha
  tags:
    -  biblestudyco_docker
  image: node
  environment: qa

job_for_beta:
  stage: beta
  before_script:
    - php -v
    - export PATH=/opt/remi/php56/root/bin/:$PATH
  script:
    - hostname
    - pwd
    - php -v
    - cd $HOME/web && git pull origin beta
    - cd $HOME/web && php artisan migrate --force --no-interaction
    - cd $HOME/web && php artisan asset:dist
    - cd $HOME/web && php artisan clear-compiled
    - cd $HOME/web && php artisan optimize
  only:
    - beta
  tags:
    - beta
  environment: staging

node_job_for_beta:
  stage: beta_node
  script:
    - export BETA_HOME=/home/bible_beta
    - cd $BETA_HOME/web
    - npm install
    - npm run build
    - find $BETA_HOME/web -user root -exec chown 1003:1003 {} \;
  only:
    - beta
  tags:
    -  biblestudyco_docker
  image: node
  environment: staging

job_for_live:
  stage: live
  before_script:
    - php -v
    - export PATH=/opt/remi/php56/root/bin/:$PATH
  script:
    - hostname
    - pwd
    - php -v
#    - cd $HOME/web && git pull origin master
#    - cd $HOME/web && php artisan migrate --force --no-interaction
#    - cd $HOME/web && php artisan asset:dist
#    - cd $HOME/web && php artisan clear-compiled
#    - cd $HOME/web && php artisan optimize
  only:
    - master
  tags:
    - live
  environment: production

node_job_for_live:
  stage: live_node
  script:
    - export LIVE_HOME=/home/bible
    - cd $LIVE_HOME/web
#    - rm -rf ./node_modules && npm i
#    - npm run build:prod
#    - find $LIVE_HOME/web -user root -exec chown 1001:1001 {} \;
  only:
    - master
  tags:
    -  biblestudyco_docker
  image: node
  environment: production