stages:
 - dev
 - dev_node
 - alpha
 - alpha_node
 - beta
 - beta_node
 - live
 - live_node

job_for_dev:
  stage: dev
  before_script:
    - export PATH=/opt/remi/php70/root/bin/:$PATH
    - path_to_vhost='/var/www/clients/client3/web1/web/'
  script:
    - cd $path_to_vhost
    - php -v
    - cd git pull origin dev
    - cd php artisan migrate --force --no-interaction
    - cd php artisan asset:dist
    - cd php artisan clear-compiled
    - cd php artisan optimize
  only:
    - dev
  tags:
    - dev
  environment: dev

node_job_for_dev:
  stage: dev_node
  before_script:
    - path_to_vhost='/var/www/clients/client3/web1/web/'
  script:
    - cd $path_to_vhost
    - node --version
    - npm install
    - npm run build
    - find $path_to_vhost -user root -exec chown 5004:5005 {} \;
  only:
    - dev
  tags:
    - sh1_clevercrew_docker
  image: node
  environment: dev

job_for_alpha:
  stage: alpha
  before_script:
    - export PATH=/opt/remi/php56/root/bin/:$PATH
    - path_to_vhost='/home/bible_alpha/web/'
  script:
    - cd $path_to_vhost
    - php -v
    - cd git pull origin alpha
    - cd php artisan migrate --force --no-interaction
    - cd php artisan asset:dist
    - cd php artisan clear-compiled
    - cd php artisan optimize
  only:
    - alpha
  tags:
    - alpha
  environment: qa

node_job_for_alpha:
  stage: alpha_node
  before_script:
    - path_to_vhost='/home/bible_alpha/web/'
  script:
    - cd $path_to_vhost
    - node --version
    - npm install
    - npm run build
    - find $path_to_vhost -user root -exec chown 1002:1002 {} \;
  only:
    - alpha
  tags:
    -  biblestudyco_docker
  image: node
  environment: qa

job_for_beta:
  stage: beta
  before_script:
    - export PATH=/opt/remi/php56/root/bin/:$PATH
    - path_to_vhost='/home/bible_beta/web/'
  script:
    - cd $path_to_vhost
    - php -v
    - cd git pull origin beta
    - cd php artisan migrate --force --no-interaction
    - cd php artisan asset:dist
    - cd php artisan clear-compiled
    - cd php artisan optimize
  only:
    - beta
  tags:
    - beta
  environment: staging

node_job_for_beta:
  stage: beta_node
  before_script:
    - path_to_vhost='/home/bible_beta/web/'
  script:
    - cd $path_to_vhost
    - node --version
    - npm install
    - npm run build
    - find $path_to_vhost -user root -exec chown 1003:1003 {} \;
  only:
    - beta
  tags:
    -  biblestudyco_docker
  image: node
  environment: staging

job_for_live:
  stage: live
  before_script:
    - export PATH=/opt/remi/php56/root/bin/:$PATH
    - path_to_vhost='/home/bible/web/'
  script:
    - cd $path_to_vhost
    - php -v
    - cd git pull origin master
    - cd php artisan migrate --force --no-interaction
    - cd php artisan asset:dist
    - cd php artisan clear-compiled
    - cd php artisan optimize
  only:
    - master
  tags:
    - live
  environment: production

node_job_for_live:
  stage: live_node
  before_script:
    - path_to_vhost='/home/bible/web/'
  script:
    - cd $path_to_vhost
    - node --version
    - rm -rf ./node_modules && npm install
    - npm run build:prod
    - find $path_to_vhost -user root -exec chown 1001:1001 {} \;
  only:
    - master
  tags:
    -  biblestudyco_docker
  image: node
  environment: production